version: '3.8'

services:
  node1:
    build: .
    ports:
      - "8081:8080"
      - "3001:3000"
    environment:
      - HASH_KEY=your-32-byte-secret-key-here!!!!
      - NODE_ADDR=:3000
      - HTTP_ADDR=:8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8081/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["./main"]

  node2:
    depends_on:
      node1:
        condition: service_healthy
    build: .
    ports:
      - "8082:8080"
      - "3002:3000"
    environment:
      - HASH_KEY=your-32-byte-secret-key-here!!!!
      - NODE_ADDR=:3000
      - HTTP_ADDR=:8080
      - BOOTSTRAP_NODES=node1:3000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8082/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["./main"]