version: "3.8"

services:
  node1:
    build: .
    ports:
      - "8081:8080"
      - "3001:3000"
    environment:
      - HASH_KEY=your-32-byte-secret-key-here!!!!
      - NODE_ADDR=:3000
      - HTTP_ADDR=:8080
    command: ["./main"]
    networks:
      - graph

  node2:
    depends_on:
      - node1
    build: .
    ports:
      - "8082:8080"
      - "3002:3000"
    environment:
      - HASH_KEY=your-32-byte-secret-key-here!!!!
      - NODE_ADDR=:3000
      - HTTP_ADDR=:8080
      - BOOTSTRAP_NODES=node1:3000
    command: ["./main"]
    networks:
      - graph

  node3:
    depends_on:
      - node2
    build: .
    ports:
      - "8083:8080"
      - "3003:3000"
    environment:
      - HASH_KEY=your-32-byte-secret-key-here!!!!
      - NODE_ADDR=:3000
      - HTTP_ADDR=:8080
      - BOOTSTRAP_NODES=node1:3000,node2:3000
    command: ["./main"]
    networks:
      - graph

networks:
  graph:
    driver: bridge
