version: "3.8"

services:
  node1:
    build: .
    ports:
      - "8081:8080"
      - "3001:3000"
    environment:
      - HASH_KEY=your-32-byte-secret-key-here!!!!
      - NODE_ADDR=:3000
      - HTTP_ADDR=:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://graph:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["./main"]
    networks:
      - graph

  node2:
    depends_on:
      - node1
    build: .
    ports:
      - "8082:8080"
      - "3002:3000"
    environment:
      - HASH_KEY=your-32-byte-secret-key-here!!!!
      - NODE_ADDR=:3000
      - HTTP_ADDR=:8080
      - BOOTSTRAP_NODES=node1:3000
    command: ["./main"]
    networks:
      - graph

networks:
  graph:
    driver: bridge
