version: '3.8'

services:
  node1:
    build: .
    ports:
      - "8081:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["./main", "-firstNode=true"]

  node2:
    depends_on:
      node1:
        condition: service_healthy
    build: .
    ports:
      - "8082:8080"
    command: ["./main", "-contactNode=127.0.0.1:8081"]