name: build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  GO_VERSION: '1.22'
  BUILD_PATH: './bin/node'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make tests

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies
        run: go mod download

      - name: Build the project
        run: make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build
          path: ${{ env.BUILD_PATH }}